source 'https://rubygems.org'

gem 'rails', '5.0.6'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '3.2.0' # lock the version to get consistent results
gem 'torba-rails', path: '../..'
gem 'rake_injector', path: '../rake_injector'
