version: 2.1

jobs:
  rails_32:
    docker:
      - image: circleci/ruby:2.3
    steps:
      - checkout
      - run: bundle install
      - restore_cache:
          keys:
            - gems-v1-rails_32-{{ checksum "test/3.2/Gemfile" }}
            - gems-v1-rails_32-
      - run:
          name: Test
          command: bundle exec rake test RAILS_VERSION=3.2
      - save_cache:
          key: gems-v1-rails_32-{{ checksum "test/3.2/Gemfile" }}
          paths:
            - test/3.2/vendor/bundle


workflows:
  test_all:
    jobs:
      - rails_32
