source 'https://rubygems.org'

gem 'rails', '4.1.16'
gem 'sass-rails', '~> 4.0.3'
gem 'sprockets', '2.12.4' # something has changed in digest algo in between 2.12.4 and 2.12.5
gem 'uglifier', '3.2.0' # lock the version to get consistent results
gem 'coffee-rails', '~> 4.0.0'
gem 'torba-rails', path: '../..'
gem 'rake_injector', path: '../rake_injector'
