source 'https://rubygems.org'

gem 'rails', '4.1.16'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'torba-rails', path: '../..'
gem 'rake_injector', path: '../rake_injector'
