source 'https://rubygems.org'

gem 'rails', '3.2.22.5'
gem 'torba-rails', path: '../..'
gem 'rake_injector', path: '../rake_injector'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '3.2.0' # lock the version to get consistent results
end
